source 'git@git.xiaojukeji.com:one-ios/Specs.git'
source 'git@git.xiaojukeji.com:mirror-pod/Spec.git'
source 'git@git.xiaojukeji.com:ios/cocoapods-specs.git'


target 'YPDemoLib_Example' do
    
  use_frameworks!
    
  pod 'YPDemoLib', :path => '../'

  target 'YPDemoLib_Tests' do
    inherit! :search_paths

    
  end
end
